package com.polyPro.ui;

import com.polyPro.utils.XShare;
import javax.swing.JOptionPane;

/**
 *
 * @author duong, cuong, vinh
 */
public class ChaoJDialog extends javax.swing.JDialog implements Runnable{

    /**
     * Creates new form ChaoJDialog
     * @param parent
     * @param modal
     */
    public ChaoJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoadingBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        lblLoading = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        BackgroundIma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(223, 238, 234));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 900, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/—Pngtree—modern flat design concept of_5332895 (4).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 410, 320));

        lblLoading.setBackground(new java.awt.Color(255, 255, 255));
        lblLoading.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLoading.setForeground(new java.awt.Color(0, 0, 0));
        lblLoading.setText("Loading ...");
        jPanel1.add(lblLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        lblName.setBackground(new java.awt.Color(255, 255, 255));
        lblName.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblName.setForeground(new java.awt.Color(61, 60, 66));
        lblName.setText("City Programming");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        LoadingValue.setBackground(new java.awt.Color(255, 255, 255));
        LoadingValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoadingValue.setForeground(new java.awt.Color(0, 0, 0));
        LoadingValue.setText("0%");
        jPanel1.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, 40, -1));

        BackgroundIma.setBackground(new java.awt.Color(223, 238, 234));
        jPanel1.add(BackgroundIma, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 500));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            ChaoJDialog dialog = new ChaoJDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundIma;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        try {
            for(int i = 0; i <= 100; i++) {
                Thread.sleep(100);
                LoadingValue.setText(i+"%");
                
                if(i == 10)
                    lblLoading.setText("Turning On Modules ...");
                if(i == 20)
                    lblLoading.setText("Loading Modules ...");
                if(i == 50)
                    lblLoading.setText("Connecting to Database ...");
                if(i == 70)
                    lblLoading.setText("Connection Successful ...");
                if(i == 80)
                    lblLoading.setText("Launching Application ...");
                LoadingBar.setValue(i);
            }
        } catch (InterruptedException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        if(LoadingBar.getValue() == 100) {
            setVisible(false);
            new DangNhapJDialog(new PolyProJFrame(), true).setVisible(true);
        }
    }
    
    private void init() {
        setIconImage(XShare.APP_ICON);
        this.setLocationRelativeTo(null);
        new Thread(this).start();
    }
}
