package com.polyPro.ui;

import com.polyPro.dao.NhanVienDAO;
import com.polyPro.model.NhanVien;
import com.polyPro.utils.Auth;
import com.polyPro.utils.XDialog;
import com.polyPro.utils.XShare;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class NhanVienJFrame extends javax.swing.JFrame {

    int index = 0; // Vi tri cua nhan vien dang hien thi tren form
    NhanVienDAO dao = new NhanVienDAO(); // DAO cua nhan vien

    public NhanVienJFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        txtXacNhanMK = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdoTruongPhong = new javax.swing.JRadioButton();
        rdoNhanVien = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        txtFind = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnFind = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage staff");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(223, 238, 234));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 82, 131));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE STAFF");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 874, 45));

        tabs.setBackground(new java.awt.Color(223, 238, 234));
        tabs.setForeground(new java.awt.Color(61, 60, 66));
        tabs.setFocusable(false);
        tabs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(223, 238, 234));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(61, 60, 66));
        jLabel2.setText("Staff ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 28, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(61, 60, 66));
        jLabel3.setText("Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 123, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(61, 60, 66));
        jLabel4.setText("Confirm password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 206, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(61, 60, 66));
        jLabel5.setText("Full name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 289, -1, -1));

        txtMaNV.setBackground(new java.awt.Color(223, 238, 234));
        txtMaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaNV.setForeground(new java.awt.Color(61, 60, 66));
        txtMaNV.setBorder(null);
        jPanel2.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 59, 810, 24));

        txtMatKhau.setBackground(new java.awt.Color(223, 238, 234));
        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMatKhau.setForeground(new java.awt.Color(61, 60, 66));
        txtMatKhau.setBorder(null);
        jPanel2.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 154, 810, 24));

        txtXacNhanMK.setBackground(new java.awt.Color(223, 238, 234));
        txtXacNhanMK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtXacNhanMK.setForeground(new java.awt.Color(61, 60, 66));
        txtXacNhanMK.setBorder(null);
        jPanel2.add(txtXacNhanMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 237, 810, 24));

        txtHoTen.setBackground(new java.awt.Color(223, 238, 234));
        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHoTen.setForeground(new java.awt.Color(61, 60, 66));
        txtHoTen.setBorder(null);
        jPanel2.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 320, 810, 24));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(61, 60, 66));
        jLabel6.setText("Role");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 372, 60, -1));

        rdoTruongPhong.setBackground(new java.awt.Color(223, 238, 234));
        buttonGroup1.add(rdoTruongPhong);
        rdoTruongPhong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        rdoTruongPhong.setForeground(new java.awt.Color(61, 60, 66));
        rdoTruongPhong.setText("Manager");
        rdoTruongPhong.setFocusPainted(false);
        jPanel2.add(rdoTruongPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 403, -1, 42));

        rdoNhanVien.setBackground(new java.awt.Color(223, 238, 234));
        buttonGroup1.add(rdoNhanVien);
        rdoNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        rdoNhanVien.setForeground(new java.awt.Color(61, 60, 66));
        rdoNhanVien.setSelected(true);
        rdoNhanVien.setText("Personnel");
        rdoNhanVien.setFocusPainted(false);
        jPanel2.add(rdoNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 403, -1, 42));

        jSeparator1.setForeground(new java.awt.Color(61, 60, 66));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 89, 820, 10));

        jSeparator2.setForeground(new java.awt.Color(61, 60, 66));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 184, 820, 10));

        jSeparator3.setForeground(new java.awt.Color(61, 60, 66));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 267, 820, 10));

        jSeparator4.setForeground(new java.awt.Color(61, 60, 66));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 350, 830, 10));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAdd.setText("INSERT");
        btnAdd.setFocusable(false);
        btnAdd.setPreferredSize(new java.awt.Dimension(92, 28));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 90, 44));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.setFocusable(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 100, 44));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.setFocusable(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 100, 44));

        btnNew.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnNew.setText("NEW");
        btnNew.setFocusable(false);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel2.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 100, 44));

        btnFirst.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnFirst.setText("|<");
        btnFirst.setFocusable(false);
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        jPanel2.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 60, 44));

        btnPre.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnPre.setText("<<");
        btnPre.setFocusable(false);
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });
        jPanel2.add(btnPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, 60, 44));

        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnNext.setText(">>");
        btnNext.setFocusable(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel2.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 60, 44));

        btnLast.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLast.setText(">|");
        btnLast.setFocusable(false);
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        jPanel2.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, 60, 44));

        tabs.addTab("UPDATE", jPanel2);

        jPanel3.setBackground(new java.awt.Color(223, 238, 234));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PASSWORD", "NAME", "ROLE"
            }
        ));
        tblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblList);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 840, 440));

        txtFind.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFindKeyPressed(evt);
            }
        });
        jPanel3.add(txtFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 10, 670, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(69, 73, 74));
        jLabel7.setText("Search:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        btnFind.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        jPanel3.add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        tabs.addTab("LIST", jPanel3);

        jPanel1.add(tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 860, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.load();
        this.setStatus(true);
    }//GEN-LAST:event_formWindowOpened

    private void tblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListMouseClicked
        if(evt.getClickCount() == 2) {
            this.index = tblList.rowAtPoint(evt.getPoint());
            if(this.index >= 0) {
                this.edit();
                tabs.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_tblListMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        this.insert();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        this.update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        this.delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        this.clear();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        this.index = 0;
        this.edit();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        this.index--;
        this.edit();
    }//GEN-LAST:event_btnPreActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        this.index++;
        this.edit();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        this.index = tblList.getRowCount() - 1;
        this.edit();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        this.load();
        this.clear();
    }//GEN-LAST:event_btnFindActionPerformed

    private void txtFindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            load();
            clear();
        }
    }//GEN-LAST:event_txtFindKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NhanVienJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoTruongPhong;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblList;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtXacNhanMK;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    private void init() {
        setIconImage(XShare.APP_ICON);
        setLocationRelativeTo(null);
        tblList.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tblList.setDefaultEditor(Object.class, null);
    }
    
    private boolean isValidate(NhanVien nv) {
        if(nv.getMaNV().equals("")) {
            XDialog.alert(this, "You ID can't be empty");
            txtMaNV.requestFocus();
            return false;
        }
        if(nv.getMatKhau().equals("")) {
            XDialog.alert(jPanel1, "You password can't be empty");
            txtMatKhau.requestFocus();
            return false;
        }
        
        if(!nv.getMatKhau().equals(txtXacNhanMK.getText())) {
            XDialog.alert(this, "Confirm password was wrong!");
            txtXacNhanMK.requestFocus();
            return false;
        }
        if(nv.getHoTen().equals("")) {
            XDialog.alert(this, "You fullname can't be empty");
            txtHoTen.requestFocus();
            return false;
        }
        return true;
    }

    /**
     * Do du lieu nhan vien tu csdl vao bang
     */
    private void load() {
        DefaultTableModel tblmodel = (DefaultTableModel) tblList.getModel();
        tblmodel.setRowCount(0);
        try {
            String keyword = txtFind.getText();
            List<NhanVien> list = dao.selectByKeyword(keyword);
            for (NhanVien nv : list) {
                Object[] row = {
                    nv.getMaNV(),
                    nv.getMatKhau(),
                    nv.getHoTen(),
                    nv.isVaiTro() ? "Manager" : "Employee"
                };
                tblmodel.addRow(row);
            }
        } catch (Exception e) {
            XDialog.alert(this, "Error data query");
        }
    }

    /**
     * Them nhan vien moi vao DB
     */
    private void insert() {
        NhanVien model = getModel();
        if(!isValidate(model)) return;
        
        try {
            dao.insert(model);
            this.load();
            this.clear();
            XDialog.alert(this, "Add staff successful!");
        } catch (Exception e) {
            XDialog.alert(this, "Add staff fail!");
        }
    }

    /**
     * Cap nhat thong tin nhan vien duoc chon tu bang
     * Nut insert, ID se vo hieu hoa
     */
    private void update() {
        NhanVien model = getModel();
        
        try {
            dao.update(model);
            this.load();
            XDialog.alert(this, "Update staff successful!");
        } catch (Exception e) {
            XDialog.alert(this, "Update staff fail!");
        }
    }

    /**
     * Xoa thong tin nhan vien da co
     */
    private void delete() {
        if(!XShare.isManager()){
            XDialog.alert(this, "You do not have permission to delete Employee!");
        }
        else{
            if(!txtMaNV.getText().equals(XShare.USER.getMaNV())) {
                if (XDialog.confirm(this, "Are you sure to delete this employee?")) {
                    String manv = txtMaNV.getText();
                    try {
                        dao.delete(manv);
                        this.load();
                        this.clear();
                        XDialog.alert(this, "Delete staff successful!");
                    } catch (Exception e) {
                        XDialog.alert(this, "Delete staff fail!");
                    }
                }
            }else XDialog.alert(this, "You can't delete yourself");
        }
    }

    /**
     * Cap nhat thong tin nhan vien
     */
    private void edit() {
        try {
            String manv = (String) tblList.getValueAt(this.index, 0);
            NhanVien model = dao.selectById(manv);
            if (model != null) {
                this.setModel(model);
                this.setStatus(false);
            }
        } catch (Exception e) {
            XDialog.alert(this, "Error data query!");
        }
    }

    /**
     * Clear form
     */
    private void clear() {
        this.setModel(new NhanVien());
        this.setStatus(true);
    }

    /**
     * Cho du lieu model len form
     * @param model la NhanVien
     */
    private void setModel(NhanVien model) {
        txtMaNV.setText(model.getMaNV());
        txtHoTen.setText(model.getHoTen());
        txtMatKhau.setText(model.getMatKhau());
        txtXacNhanMK.setText("");
        rdoTruongPhong.setSelected(model.isVaiTro());
        rdoNhanVien.setSelected(!model.isVaiTro());
    }

    /**
     * Doc thong tin form
     * @return tra ve NhanVien
     */
    private NhanVien getModel() {
        NhanVien model = new NhanVien();
        model.setMaNV(txtMaNV.getText());
        model.setHoTen(txtHoTen.getText());
        model.setMatKhau(txtMatKhau.getText());
        model.setVaiTro(rdoTruongPhong.isSelected());
        return model;
    }

    /**
     * 
     * @param insertable la gia tri 
     */
    private void setStatus(boolean insertable) {
        txtMaNV.setEditable(insertable);
        btnAdd.setEnabled(insertable);
        btnUpdate.setEnabled(!insertable);
        btnDelete.setEnabled(!insertable);

        boolean first = this.index > 0;
        boolean last = this.index < tblList.getRowCount() - 1;
        btnFirst.setEnabled(!insertable && first);
        btnPre.setEnabled(!insertable && first);
        btnNext.setEnabled(!insertable && last);
        btnLast.setEnabled(!insertable && last);
    }
}
