package com.polyPro.ui;

import com.polyPro.utils.Auth;
import com.polyPro.utils.XDialog;
import com.polyPro.utils.XShare;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class PolyProJFrame extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form PolyPro
     */
    public PolyProJFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        btnKetThuc = new javax.swing.JButton();
        btnChuyenDe = new javax.swing.JButton();
        btnNguoiHoc = new javax.swing.JButton();
        btnKhoaHoc = new javax.swing.JButton();
        btnHuongDan = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnItemDangNhap = new javax.swing.JMenuItem();
        mnItemDangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnItemDMK = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnItemKetThuc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnNguoiHoc = new javax.swing.JMenuItem();
        mnChuyenDe = new javax.swing.JMenuItem();
        mnKhoaHoc = new javax.swing.JMenuItem();
        mnNhanVien = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnThongKeNguoiHoc = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnTKDiemKhoaHoc = new javax.swing.JMenuItem();
        mnTKDiem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnTKDoanhThu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnUse = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(223, 238, 234));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Info.png"))); // NOI18N
        jLabel2.setText("Training management system");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 260, 30));

        lblClock.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClock.setForeground(new java.awt.Color(255, 0, 51));
        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Alarm.png"))); // NOI18N
        lblClock.setText("00:00:00");
        jPanel1.add(lblClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 160, 30));

        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Exit.png"))); // NOI18N
        btnDangXuat.setText("Logout");
        btnDangXuat.setFocusPainted(false);
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnKetThuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Stop.png"))); // NOI18N
        btnKetThuc.setText("Exit");
        btnKetThuc.setFocusPainted(false);
        btnKetThuc.setFocusable(false);
        btnKetThuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKetThuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });
        jPanel1.add(btnKetThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 10, 70, -1));

        btnChuyenDe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Lists.png"))); // NOI18N
        btnChuyenDe.setText("Thematic");
        btnChuyenDe.setFocusPainted(false);
        btnChuyenDe.setFocusable(false);
        btnChuyenDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyenDe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenDeActionPerformed(evt);
            }
        });
        jPanel1.add(btnChuyenDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        btnNguoiHoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Conference.png"))); // NOI18N
        btnNguoiHoc.setText("Learner");
        btnNguoiHoc.setFocusPainted(false);
        btnNguoiHoc.setFocusable(false);
        btnNguoiHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNguoiHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguoiHocActionPerformed(evt);
            }
        });
        jPanel1.add(btnNguoiHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        btnKhoaHoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Certificate.png"))); // NOI18N
        btnKhoaHoc.setText("Course");
        btnKhoaHoc.setFocusPainted(false);
        btnKhoaHoc.setFocusable(false);
        btnKhoaHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhoaHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaHocActionPerformed(evt);
            }
        });
        jPanel1.add(btnKhoaHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        btnHuongDan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Globe.png"))); // NOI18N
        btnHuongDan.setText("Manual");
        btnHuongDan.setFocusPainted(false);
        btnHuongDan.setFocusable(false);
        btnHuongDan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuongDan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuongDanActionPerformed(evt);
            }
        });
        jPanel1.add(btnHuongDan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 880, 10));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, 70));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, 330));

        jMenuBar1.setBackground(new java.awt.Color(223, 238, 234));

        jMenu1.setText("System");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnItemDangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnItemDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnItemDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/key.png"))); // NOI18N
        mnItemDangNhap.setText("Login");
        mnItemDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemDangNhapActionPerformed(evt);
            }
        });
        jMenu1.add(mnItemDangNhap);

        mnItemDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnItemDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnItemDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Log out.png"))); // NOI18N
        mnItemDangXuat.setText("Logout");
        mnItemDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mnItemDangXuat);
        jMenu1.add(jSeparator1);

        mnItemDMK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnItemDMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Refresh.png"))); // NOI18N
        mnItemDMK.setText("Change password");
        mnItemDMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemDMKActionPerformed(evt);
            }
        });
        jMenu1.add(mnItemDMK);
        jMenu1.add(jSeparator2);

        mnItemKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mnItemKetThuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnItemKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Stop.png"))); // NOI18N
        mnItemKetThuc.setText("Exit");
        mnItemKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemKetThucActionPerformed(evt);
            }
        });
        jMenu1.add(mnItemKetThuc);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Manage");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnNguoiHoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Conference.png"))); // NOI18N
        mnNguoiHoc.setText("Learner");
        mnNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNguoiHocActionPerformed(evt);
            }
        });
        jMenu2.add(mnNguoiHoc);

        mnChuyenDe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Lists.png"))); // NOI18N
        mnChuyenDe.setText("Thematic");
        mnChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnChuyenDeActionPerformed(evt);
            }
        });
        jMenu2.add(mnChuyenDe);

        mnKhoaHoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Certificate.png"))); // NOI18N
        mnKhoaHoc.setText("Course");
        mnKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKhoaHocActionPerformed(evt);
            }
        });
        jMenu2.add(mnKhoaHoc);

        mnNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/User group.png"))); // NOI18N
        mnNhanVien.setText("Staff");
        mnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNhanVienActionPerformed(evt);
            }
        });
        jMenu2.add(mnNhanVien);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Statistical");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnThongKeNguoiHoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnThongKeNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Clien list.png"))); // NOI18N
        mnThongKeNguoiHoc.setText("Learners every year");
        mnThongKeNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnThongKeNguoiHocActionPerformed(evt);
            }
        });
        jMenu3.add(mnThongKeNguoiHoc);
        jMenu3.add(jSeparator3);

        mnTKDiemKhoaHoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnTKDiemKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Card file.png"))); // NOI18N
        mnTKDiemKhoaHoc.setText("Course transcript");
        mnTKDiemKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTKDiemKhoaHocActionPerformed(evt);
            }
        });
        jMenu3.add(mnTKDiemKhoaHoc);

        mnTKDiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnTKDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/bar-chart.png"))); // NOI18N
        mnTKDiem.setText("Scores for each course");
        mnTKDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTKDiemActionPerformed(evt);
            }
        });
        jMenu3.add(mnTKDiem);
        jMenu3.add(jSeparator4);

        mnTKDoanhThu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnTKDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Dollar.png"))); // NOI18N
        mnTKDoanhThu.setText("Revenue from each thematic");
        mnTKDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTKDoanhThuActionPerformed(evt);
            }
        });
        jMenu3.add(mnTKDoanhThu);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnUse.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnUse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnUse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Globe.png"))); // NOI18N
        mnUse.setText("Manual");
        mnUse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUseActionPerformed(evt);
            }
        });
        jMenu4.add(mnUse);
        jMenu4.add(jSeparator5);

        mnAbout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/polyPro/icon/Brick house.png"))); // NOI18N
        mnAbout.setText("About");
        mnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutActionPerformed(evt);
            }
        });
        jMenu4.add(mnAbout);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnItemDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemDangNhapActionPerformed
        this.openLogin();
    }//GEN-LAST:event_mnItemDangNhapActionPerformed

    private void mnItemDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemDangXuatActionPerformed
        this.logoff();
    }//GEN-LAST:event_mnItemDangXuatActionPerformed

    private void mnItemKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemKetThucActionPerformed
        this.exit();
    }//GEN-LAST:event_mnItemKetThucActionPerformed

    private void mnNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNguoiHocActionPerformed
        this.openNguoiHoc();
    }//GEN-LAST:event_mnNguoiHocActionPerformed

    private void mnChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnChuyenDeActionPerformed
        this.openChuyenDe();
    }//GEN-LAST:event_mnChuyenDeActionPerformed

    private void mnKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKhoaHocActionPerformed
        this.openKhoaHoc();
    }//GEN-LAST:event_mnKhoaHocActionPerformed

    private void mnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNhanVienActionPerformed
        this.openNhanVien();
    }//GEN-LAST:event_mnNhanVienActionPerformed

    private void mnThongKeNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnThongKeNguoiHocActionPerformed
        this.openThongKe(0);
    }//GEN-LAST:event_mnThongKeNguoiHocActionPerformed

    private void mnTKDiemKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTKDiemKhoaHocActionPerformed
        this.openThongKe(1);
    }//GEN-LAST:event_mnTKDiemKhoaHocActionPerformed

    private void mnTKDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTKDiemActionPerformed
        this.openThongKe(2);
    }//GEN-LAST:event_mnTKDiemActionPerformed

    private void mnTKDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTKDoanhThuActionPerformed
        this.openThongKe(3);
    }//GEN-LAST:event_mnTKDoanhThuActionPerformed

    private void mnUseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUseActionPerformed
        this.openWebsite();

    }//GEN-LAST:event_mnUseActionPerformed

    private void mnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutActionPerformed
        this.openAbout();
    }//GEN-LAST:event_mnAboutActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        this.logoff();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        this.exit();
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void btnChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenDeActionPerformed
        this.openChuyenDe();
    }//GEN-LAST:event_btnChuyenDeActionPerformed

    private void btnNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguoiHocActionPerformed
        this.openNguoiHoc();
    }//GEN-LAST:event_btnNguoiHocActionPerformed

    private void btnKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaHocActionPerformed
        this.openKhoaHoc();
    }//GEN-LAST:event_btnKhoaHocActionPerformed

    private void btnHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuongDanActionPerformed
        this.openWebsite();
    }//GEN-LAST:event_btnHuongDanActionPerformed

    private void mnItemDMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemDMKActionPerformed
        this.openQuenMK();
    }//GEN-LAST:event_mnItemDMKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolyProJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolyProJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolyProJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolyProJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PolyProJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyenDe;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHuongDan;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnKhoaHoc;
    private javax.swing.JButton btnNguoiHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblClock;
    private javax.swing.JMenuItem mnAbout;
    private javax.swing.JMenuItem mnChuyenDe;
    private javax.swing.JMenuItem mnItemDMK;
    private javax.swing.JMenuItem mnItemDangNhap;
    private javax.swing.JMenuItem mnItemDangXuat;
    private javax.swing.JMenuItem mnItemKetThuc;
    private javax.swing.JMenuItem mnKhoaHoc;
    private javax.swing.JMenuItem mnNguoiHoc;
    private javax.swing.JMenuItem mnNhanVien;
    private javax.swing.JMenuItem mnTKDiem;
    private javax.swing.JMenuItem mnTKDiemKhoaHoc;
    private javax.swing.JMenuItem mnTKDoanhThu;
    private javax.swing.JMenuItem mnThongKeNguoiHoc;
    private javax.swing.JMenuItem mnUse;
    // End of variables declaration//GEN-END:variables

    /**
     * Hien gio
     */
    @Override
    public void run() {
        while (true) {
            Date date = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat();
            sdf.applyPattern("hh:mm:ss aa");
            String time = sdf.format(date);
            lblClock.setText(time);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                break;
            }
        }
    }

    /**
     * Set
     */
    private void init() {
        setIconImage(XShare.APP_ICON);
        setLocationRelativeTo(null);
        new Thread(this).start();
    }

    /**
     * Mo form login Loi: Sau khi login thanh cong, se mo them 1 form polyPro ->
     * Bi thanh 2 form Khac phuc: Sau khi dang nhap thanh cong, quay tro lai
     * form cu hoac tat form cu va mo form moi Trang thai: Hoan thanh
     */
    private void openLogin() {
        if (XShare.authenticated()) {
            XDialog.alert(this, "You has login");
        } else {
            new DangNhapJDialog(this, true).setVisible(true);
            this.dispose();
        }
    }

    /**
     * Dang xuat khoi tai khoan -> mo form dang nhap
     */
    private void logoff() {
        if (XShare.authenticated()) {
            XShare.logoff();
            this.openLogin();
        } else {
            XDialog.alert(this, "Please login");
        }

    }

    private void openQuenMK() {
        if (XShare.authenticated()) {
            new DoiMKJDialog(this, true).setVisible(true);
        } else {
            XDialog.alert(this, "Please login");
        }
    }

    /**
     * Thoat khoi chuong trinh
     */
    private void exit() {
        if (XDialog.confirm(this, "Are you sure to logout?")) {
            System.exit(0);
        }
    }

    /**
     * Mo form thong ke
     *
     * @param index la tabs thong ke muon mo
     */
    private void openThongKe(int index) {
        if(XShare.authenticated()){
            if(index == 3 && !XShare.isManager()){
                XDialog.alert(this, "You can't access");
                return;
            }
            ThongKeJFrame tkwin = new ThongKeJFrame();
            tkwin.selectTab(index);
            tkwin.setVisible(true);
        } else {
            XDialog.alert(this, "Please login!");
        }
    }

    /**
     * Mo form nhan vien
     */
    private void openNhanVien() {
        if (XShare.authenticated()) {
            new NhanVienJFrame().setVisible(true);
        } else {
            XDialog.alert(this, "Please login!");
        }
    }

    /**
     * Mo form khoa hoc
     */
    private void openKhoaHoc() {
        if (XShare.authenticated()) {
            new KhoaHocJFrame().setVisible(true);
        } else {
            XDialog.alert(this, "Please login!");
        }
    }

    /**
     * Mo form chuyen de
     */
    private void openChuyenDe() {
        if (XShare.authenticated()) {
            new ChuyenDeJFrame().setVisible(true);
        } else {
            XDialog.alert(this, "Please login!");
        }
    }

    /**
     * Mo form nguoi hoc
     */
    private void openNguoiHoc() {
        if (XShare.authenticated()) {
            new NguoiHocJFrame().setVisible(true);
        } else {
            XDialog.alert(this, "Please login!");
        }
    }

    /**
     * Mo form gioi thieu
     */
    private void openAbout() {
        new GioiThieuJDialog(this, true).setVisible(true);
    }

    /**
     * Mo website
     */
    private void openWebsite() {
        try {
            Desktop.getDesktop().browse(new File("dist\\help\\index.html").toURI());
        } catch (IOException ex) {
            XDialog.alert(this, "Can't find url image!");
            System.out.println(ex);
        }
    }

}
